CREATE TABLE IF NOT EXISTS Genre (
id SERIAL PRIMARY KEY,
Name VARCHAR(57) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist (
id SERIAL PRIMARY KEY,
Name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS GenreArtist (
Genre_id INTEGER REFERENCES Genre(id),
Artist_id INTEGER REFERENCES Artist(id),
CONSTRAINT Gen_Art PRIMARY KEY (Genre_id, Artist_id)
);

CREATE TABLE IF NOT EXISTS Album (
id SERIAL PRIMARY KEY,
Name VARCHAR(120) NOT NULL,
Release_Year DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistAlbum (
Artist_id INTEGER REFERENCES Artist(id),
Album_id INTEGER REFERENCES Album(id),
CONSTRAINT Art_Alb PRIMARY KEY (Artist_id, Album_id)
);

CREATE TABLE IF NOT EXISTS Track (
id SERIAL PRIMARY KEY,
Name VARCHAR(120) NOT NULL,
Lasting TIME NOT NULL,
Album_id INTEGER REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Collection (
id SERIAL PRIMARY KEY,
Name VARCHAR(150) NOT NULL,
Release_Year DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CollectionTrack (
collection_id INTEGER REFERENCES collection(id),
track_id INTEGER REFERENCES track(id),
CONSTRAINT col_trk PRIMARY KEY (collection_id, track_id)
);